#
# test-builds.yml
# Do test builds to catch compile errors
#

name: CI

on:
  pull_request:
    branches:
    - bugfix-2.0.x
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'
  push:
    branches:
    - bugfix-2.0.x
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  test_builds:
    name: Run All Tests
    if: github.repository == 'MarlinFirmware/Marlin'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-platform:
        # Base Environments

        - DUE
        - esp32
        - linux_native
        - mega2560
        - teensy31
        - teensy35
        - teensy41
        - SAMD51_grandcentral_m4

        # Extended AVR Environments

        - FYSETC_F6_13
        - mega1280
        - rambo
        - sanguino1284p
        - sanguino644p

        # Extended STM32 Environments

        #- STM32F103RC_btt_maple
        - STM32F103RC_btt_USB_maple
        - STM32F103RC_fysetc_maple
        - STM32F103RC_meeb_maple
        - jgaurora_a5s_a1_maple
        - STM32F103VE_longer_maple
        #- mks_robin_maple
        - mks_robin_lite_maple
        - mks_robin_pro_maple
        #- mks_robin_nano35_maple
        #- STM32F103RE_creality_maple
        - STM32F103VE_ZM3E4V2_USB_maple

        # STM32 (ST) Environments

        - STM32F103RC_btt
        #- STM32F103RC_btt_USB
        - STM32F103RE_btt
        - STM32F103RE_btt_USB
        - STM32F103RE_creality
        - STM32F401RC_creality
        - STM32F103VE_longer
        - STM32F407VE_black
        - STM32F401VE_STEVAL
        - BIGTREE_BTT002
        - BIGTREE_SKR_PRO
        - BIGTREE_GTR_V1_0
        - mks_robin
        - mks_robin_stm32
        - ARMED
        - FYSETC_S6
        - STM32F070CB_malyan
        - STM32F070RB_malyan
        - malyan_M300
        - mks_robin_lite
        - FLYF407ZG
        - rumba32
        - mks_robin_pro
        - STM32F103RET6_creality
        - LERDGEX
        - LERDGEK
        - mks_robin_nano35
        - NUCLEO_F767ZI
        - REMRAM_V1
        - BTT_SKR_SE_BX
        - chitu_f103
        - Index_Mobo_Rev03

        # Put lengthy tests last

        - LPC1768
        - LPC1769

        # STM32 with non-STM framework. both broken for now. they should use HAL_STM32 which is working.

        #- STM32F4
        #- STM32F7

        # Non-working environment tests
        #- at90usb1286_cdc
        #- at90usb1286_dfu
        #- STM32F103CB_malyan
        #- mks_robin_mini

    steps:

    - name: Check out the PR
      uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Select Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U platformio
        pio upgrade --dev
        pio pkg update --global

    - name: Run ${{ matrix.test-platform }} Tests
      run: |
        # Inline tests script
        chmod +x buildroot/bin/*
        chmod +x buildroot/tests/*
        export PATH=./buildroot/bin/:./buildroot/tests/:${PATH}
        run_tests . ${{ matrix.test-platform }}
